### ISSUE TITLE
Part ID 390227-06 associated with two parts

### ISSUE THREAD

**Issue by Jymper** [shred/a500-bom#1]
Greetings,

The two parts listed below have the same Part ID on the BOM.

Part ID           Qty    Part
390227-06	2	74HCT245, Octal Tri-State Bus Transceiver 
390227-06	2	47Ω Isolated Resistor Network, 5 Elements 

I ran across this while doing some double checking in Excel.

I did a little digging and found the a500_rev.8_-_service_manual. These two parts are listed with the same part number in the service manual. 😒

Best Regards!

**Comment by shred** [comment]
Good catch, thank you! :smile: 

You are right, the part ID was already wrong in the original Commodore service manual. I found a comprehensive [Commodore Spare Part List](https://archive.org/details/commodore-ersatzteilliste-02-92) with the correct number, and fixed it.
